apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.global.namespace}}
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.replicas}}
  strategy:
    type: {{.Values.strategy.type}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      name: {{.Chart.Name}}
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: {{.Values.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
            - name: {{.Chart.Name}}
              containerPort: {{.Values.ports.containerPort}}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
      restartPolicy: {{.Values.restartPolicy}}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      imagePullSecrets:
        - name: gitlab-registry-secret