apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.global.namespace}}
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
spec:
  selector:
    app: {{.Chart.Name}}
  ports:
    - protocol: TCP
      port: {{.Values.ports.containerPort}}
      targetPort: {{.Values.ports.targetPort}}
  type: ClusterIP
  