stages:
  - build
  - release

variables:
  CHART_NAME: momo-store-chart
  CHART_VERSION: 1.0.${CI_PIPELINE_ID}

build:
  stage: build
  image: alpine/helm:3.8.0
  script:
    - helm dependency update ${CHART_NAME}
    - helm lint ${CHART_NAME}
    - helm package ${CHART_NAME} --version ${CHART_VERSION} --destination .
  artifacts:
    paths:
      - momo-store-${CHART_VERSION}.tgz

release:
  stage: release
  image: curlimages/curl
  script:
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} $NEXUS_HELM_REPO --upload-file momo-store-${CHART_VERSION}.tgz