apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.global.namespace}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: {{.Values.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
            - name: {{.Chart.Name}}
              containerPort: {{.Values.ports.containerPort}}
      imagePullSecrets:
        - name: gitlab-registry-secret