apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.global.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.ports.containerPort}}
      protocol: TCP
      targetPort: {{.Values.ports.targetPort}}
  selector:
    app: {{.Chart.Name}}
  